### ISSUE TITLE
Godin filter function fails with Pandas 1.1

### ISSUE THREAD

**Issue by bradtom** [CADWRDeltaModeling/vtools3#21]
**Test code:**
import pandas as pd
import pyhecdss
import vtools
from vtools.functions.filter import godin

path_spec = '//SSS/////'
#print('about to read data for filename, path_spec='+dss_filename_dict[study]+','+path_spec)
df_list = pyhecdss.get_rts('cdec_ec_merged_sep2020.dss', path_spec)
df = df_list[0][0]
dss_path = df.columns.values[0]
parts = dss_path.split('/')
e_part = parts[5]
df = df.resample(e_part).mean()
godin_df = godin(df)
**Error message:**
Traceback (most recent call last):
  File "testDss.py", line 15, in <module>
    godin_df = godin(df)
  File "C:\Users\btom\Anaconda3\envs\dms2\lib\site-packages\vtools\functions\filter.py", line 346, in godin
    godin_ir=generate_godin_fir(freq)
  File "C:\Users\btom\Anaconda3\envs\dms2\lib\site-packages\vtools\functions\filter.py", line 295, in generate_godin_fir
    if freq in _cached_filt_info:
TypeError: unhashable type: 'pandas._libs.tslibs.offsets.Minute'

**Comment by dwr-psandhu** [comment]
@esatel Were you able to reproduce this issue?

**Comment by water-e** [comment]
Trying to address a few issues that are lingering. Is this still live? If so can you submit a test file that is 1) tiny (10 days) and 2) not dss dependent? Otherwise I'll close it.

**Comment by dwr-psandhu** [comment]
@water-e Fixed by me a year ago.
See commit https://github.com/CADWRDeltaModeling/vtools3/commit/13e4f1c9de37b8197c5817aaae2788e7710370b2

If you want to add a smoke test something like this will work without any reference to dss
```
import pandas as pd
import numpy as np


import vtools
from vtools.functions.filter import godin

n=1000
df=pd.DataFrame(data=np.random.rand(n),index=pd.date_range(start='01JAN1990 0100',periods=n,freq='15MIN'))
godin(df).plot()
```
