### ISSUE TITLE
versioneer conflict 

### ISSUE THREAD

**Issue by HansKimDWR** [CADWRDeltaModeling/vtools3#45]
# Issue
When attempting to install vtools3 with `pip install -e .`, following error with versioneer is encountered:

![MicrosoftTeams-image](https://github.com/CADWRDeltaModeling/vtools3/assets/57460514/35302a23-caff-4ad2-9be7-662c65938793)

This issue has been reported in the versioneer repo:
https://github.com/python-versioneer/python-versioneer/issues/375

# Solution
Use python version 3.11 or lower.

**Comment by effigies** [comment]
This has been fixed for a while, but an old versioneer is vendored here. Upgrade with `pipx run versioneer install`.

See https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md for any migration issues.

**Comment by tmpnemophd** [comment]
Thank you. Using Python=3.11 solved the issue.

**Comment by HansKimDWR** [comment]
Thank you. Using python version 3.11 solved the issue.
