### ISSUE TITLE
vtools depends on dms_datastore and dms_datastore depends on vtools

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/vtools3#46]
circular dependency (see example below)

https://github.com/CADWRDeltaModeling/vtools3/blob/86accf7e1eab9e46005d175c1170876a6f8e9ebe/vtools/data/gap.py#L5

https://github.com/CADWRDeltaModeling/dms_datastore/blob/42ae711454a6a6646ef1e1577b641094a68c4553/dms_datastore/auto_screen.py#L15

**Comment by water-e** [comment]
Just an unused import. Fixed
